[libclang/python] Add missing concept declaration CursorKind (#69125)
Maps to
[`CXCursor_ConceptDecl`](https://github.com/llvm/llvm-project/blob/ee8524087c78a673fcf5486ded69ee597a85e0f1/clang/include/clang-c/Index.h#L2716),
added in ee8524087c78a673fcf5486ded69ee597a85e0f1.

Without this I get this error on my codebase which uses C++20 concept
decls:
```
ValueError: Unknown template argument kind 604
```