[clang][dataflow] Fix build failure due to -Wunused-variable in DataflowEnvironment.cpp (NFC)
/data/llvm-project/clang/lib/Analysis/FlowSensitive/DataflowEnvironment.cpp:125:11: error: unused variable 'StructVal2' [-Werror,-Wunused-variable]
    auto *StructVal2 = cast<StructValue>(&Val2);
          ^
1 error generated.