[Analysis] Fix an unused variable warning
This patch fixes:

  llvm/lib/Analysis/LoopAccessAnalysis.cpp:2001:12: error: unused
  variable 'MinDepDistBytesOld' [-Werror,-Wunused-variable]